version: "3.7"
services:
  sql-server-db-fastify-api:
    container_name: sql-server-db-fastify-api
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"

# username sa